### ISSUE TITLE
"Error:" without message on startup

### ISSUE THREAD

**Issue by adamcharnock** [tantalic/dropbox-oneway#1]
First, this project is exactly what I need, thank you. However, I get an error upon startup. All I see is:

```
$ docker run -e DROPBOX_TOKEN=mytoken -e DROPBOX_DIRECTORY=ExampleDirectory -e LOCAL_DIRECTORY=/root tantalic/dropbox-oneway:v0.1.1
2017/06/06 15:02:04 Starting dropbox-oneway (v0.1.1)
2017/06/06 15:02:05 Error:
```

Sadly this is no error message. I would like to petition for there being an error message :-)

**Comment by adamcharnock** [comment]
Ah, ignore that. ``DROPBOX_DIRECTORY=ExampleDirectory`` should have been ``DROPBOX_DIRECTORY=/ExampleDirectory``

**Comment by tantalic** [comment]
@adamcharnock - Thanks for filing an issue. Glad you solved your issue, but I will definitely improve the error message. Any other feedback or suggestions are welcome!

**Comment by adamcharnock** [comment]
Thank you @tantalic. My only nice-to-have would be lower memory consumption. However, it currently takes 4x less than the official Dropbox client (200Mb vs 800Mb in my use case), so I'm already spoilt :-)
